spring:
  datasource:
    url: jdbc:mysql://192.168.3.181:3306/mini_admin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
